### PR TITLE
Resolve syncing conflicts from master-sync-work to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from master-sync-work to master.

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-cli-python, working directory: W:\05am-s, target branch: master, target branch commit: 01b3c24d15cb6144a65764f42dc8f63c56f4ed40, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C3%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708031544413693-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-cli-python, working directory: W:\kood-s, target branch: master, target branch commit: 01b3c24d15cb6144a65764f42dc8f63c56f4ed40, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C9%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708090521252951-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-cli-python, working directory: W:\k4gd-s, target branch: master, target branch commit: 01b3c24d15cb6144a65764f42dc8f63c56f4ed40, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C9%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708091558390121-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit 3b6cd6a951862486bf0d115337da092ad2006963 in branch master-sync-work of repository https://github.com/OPS-E2E-Prod/azure-docs-cli-python into branch master (commit 01b3c24d15cb6144a65764f42dc8f63c56f4ed40)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C9%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708091602139051-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OPS-E2E-Prod/azure-docs-cli-python, working directory: W:\qu3y-s, target branch: master, target branch commit: 01b3c24d15cb6144a65764f42dc8f63c56f4ed40, source branch: master-sync-work, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C11%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708112133158211-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/vm/image?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/account.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/account.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/account?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acr.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acr.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acr/credential.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acr/credential.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr/credential?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acr/repository.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acr/repository.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr/repository?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acr/webhook.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acr/webhook.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr/webhook?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acs.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acs?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acs/dcos.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acs/dcos.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acs/dcos?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/acs/kubernetes.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/acs/kubernetes.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acs/kubernetes?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad/app.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/app?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad/group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group/member.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad/group/member.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/group/member?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad/sp.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/sp?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/user.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/ad/user.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/user?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/appservice.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/appservice.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/appservice?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/appservice/plan.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/appservice/plan.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/appservice/plan?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/account.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/account.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/account?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/account/autostorage-keys.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/account/autostorage-keys.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/account/autostorage-keys?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/account/keys.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/account/keys.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/account/keys?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/application.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/application.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/application?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/application/package.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/application/package.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/application/package?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/application/summary.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/application/summary.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/application/summary?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/certificate.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/certificate.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/certificate?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/job-schedule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/job-schedule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/job-schedule?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/job.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/job.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/job?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/job/all-statistics.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/job/all-statistics.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/job/all-statistics?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/job/prep-release-status.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/job/prep-release-status.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/job/prep-release-status?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/location.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/location.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/location?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/location/quotas.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/location/quotas.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/location/quotas?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node/file.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node/file.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node/file?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node/remote-desktop.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node/remote-desktop.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node/remote-desktop?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node/remote-login-settings.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node/remote-login-settings.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node/remote-login-settings?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node/scheduling.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node/scheduling.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node/scheduling?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/node/user.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/node/user.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/node/user?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool/all-statistics.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool/all-statistics.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool/all-statistics?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool/autoscale.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool/autoscale.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool/autoscale?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool/node-agent-skus.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool/node-agent-skus.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool/node-agent-skus?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool/os.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool/os.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool/os?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/pool/usage-metrics.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/pool/usage-metrics.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/pool/usage-metrics?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/task.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/task.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/task?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/task/file.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/task/file.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/task/file?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/batch/task/subtask.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/batch/task/subtask.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/batch/task/subtask?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/billing.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/billing.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/billing?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/billing/invoice.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/billing/invoice.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/billing/invoice?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/billing/period.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master-sync-work/2017-03-09-profile/docs-ref-autogen/billing/period.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/billing/period?view=azure-cli-2017-03-09-profile&branch=pr-en-us-8) (azure-cli-2017-03-09-profile) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C17%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201708170751398652-8%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
