### PR TITLE
merge master into live-based

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-peliao-zz** [comment]
OPS Build status updates of commit _[2fdab54](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/2fdab545c6f858062f6662e09b98bb73e76f074d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[2fdab54](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/2fdab545c6f858062f6662e09b98bb73e76f074d)_: 

:clock10: **Incremental building**: average incremental building time is _11 min(s) 53 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[2fdab54](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/2fdab545c6f858062f6662e09b98bb73e76f074d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-2017-03-09-profile&branch=pr-en-us-48) (azure-cli-2017-03-09-profile) |
[2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-48) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-48) (azure-cli-2018-03-01-hybrid) |
[latest/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-latest&branch=pr-en-us-48) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-latest&branch=pr-en-us-48) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201901070622166383-48%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qh%2F15Q2cg6kIsMta6NiBXActnvqqJB%2FzBYxM5t8asns%3D&st=2019-01-07T06%3A32%3A14Z&se=2019-02-07T06%3A37%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[f063503](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/f06350393e11c7a1354f49e82004e55269d19816)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 11 sec(s)_

**Comment by v-peliao-zz** [comment]
OPS Build status updates of commit _[f063503](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/f06350393e11c7a1354f49e82004e55269d19816)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 11 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[f063503](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/48/commits/f06350393e11c7a1354f49e82004e55269d19816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-2017-03-09-profile&branch=pr-en-us-48) (azure-cli-2017-03-09-profile) |
[2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-48) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-48) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-latest&branch=pr-en-us-48) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2017-03-09-profile&branch=pr-en-us-48) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-48) (azure-cli-2018-03-01-hybrid) |
[latest/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-latest&branch=pr-en-us-48) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/storage-preview/storage/blob/service-properties.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/blob/service-properties?view=azure-cli-latest&branch=pr-en-us-48) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201901072244493116-48%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=B0BaW6Lyk1WVnurVfBeOe67jB2JCXbuqJ9NSMPaJuFs%3D&st=2019-01-07T22%3A53%3A03Z&se=2019-02-07T22%3A58%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
