### PR TITLE
Merge master into live-based

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[6b3ad71](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/commits/6b3ad716328e6a6c24055c89576491701b82473d)_: 

:clock10: **Full build**: the average full build time is _7 min(s) 16 sec(s)_, this is based on the last _88_ build(s) for this repository.

**Comment by e2ebd5** [comment]
Docs Build status updates of commit _[6b3ad71](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/commits/6b3ad716328e6a6c24055c89576491701b82473d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5d841c44)

<a id="5d841c44"></a>
###
 - **Line 390**: **[Error]** `````Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in https://SiteHelp and include the following error message for our team to troubleshoot: Cannot process argument transformation on parameter 'defaultBoolValue'. Cannot convert value "" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C25%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C202005250943032744-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JhB%2FuFvtAbL5NL7lqcg4n9LE%2BUvLsWj0mLkrG3RIBHw%3D&st=2020-05-25T09%3A58%3A15Z&se=2020-06-25T10%3A03%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0762c6d6-cb91-510a-10b9-a881d0bb3e83?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[6b3ad71](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/commits/6b3ad716328e6a6c24055c89576491701b82473d)_: 

:clock10: **Full build**: the average full build time is _7 min(s) 17 sec(s)_, this is based on the last _89_ build(s) for this repository.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[6b3ad71](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/commits/6b3ad716328e6a6c24055c89576491701b82473d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/aks-preview/aks.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks/nodepool?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/routing-rule?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/rules-engine/rule?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile) |
[2018-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks/nodepool?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/routing-rule?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/rules-engine/rule?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[2019-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2019-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks.yml) | :white_check_mark:Succeeded | |
[2019-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2019-03-01-hybrid/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml) | :white_check_mark:Succeeded | |
[2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door.yml) | :white_check_mark:Succeeded | |
[2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml) | :white_check_mark:Succeeded | |
[2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2019-03-01-hybrid/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2017-03-09-profile&branch=pr-en-us-99) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-99) (azure-cli-2018-03-01-hybrid) |
[latest/docs-ref-autogen/acr/scope-map.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/scope-map.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr/scope-map?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/acr/token.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/token.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/acr/token?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/aks-preview/aks.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/aks-preview/aks.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/aks-preview/aks/nodepool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/aks-preview/aks/nodepool?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/front-door/network/front-door.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/front-door/network/front-door/routing-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/routing-rule?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |
[latest/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ext/front-door/network/front-door/rules-engine/rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/front-door/network/front-door/rules-engine/rule?view=azure-cli-latest&branch=pr-en-us-99) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C26%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C202005260342082001-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nm12tHYyOT%2FNMd%2F1cZwbuo%2FJLlMA9aBIxnLRPzAFVKk%3D&st=2020-05-26T03%3A51%3A26Z&se=2020-06-26T03%3A56%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/0762c6d6-cb91-510a-10b9-a881d0bb3e83?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
