### PR TITLE
merge master into live-based

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by v-peliao-zz** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

:clock10: **Incremental building**: average incremental building time is _11 min(s) 22 sec(s)_

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[80cbbe5](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/47/commits/80cbbe5900573fa19160e945f69e26f1048d29c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2017-03-09-profile/docs-ref-autogen/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/traffic-manager/endpoint?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/account.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/account.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/account?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/account/lock.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/account/lock.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/account/lock?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/account/management-group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/account/management-group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/account/management-group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/account/management-group/subscription.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/account/management-group/subscription.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/account/management-group/subscription?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/app.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/app?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app/credential.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/app/credential.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/app/credential?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app/owner.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/app/owner.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/app/owner?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/app/permission.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/app/permission.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/app/permission?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group/member.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/group/member.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/group/member?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/group/owner.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/group/owner.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/group/owner?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/signed-in-user.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/signed-in-user.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/signed-in-user?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/sp.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/sp?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp/credential.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/sp/credential.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/sp/credential?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/sp/owner.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/sp/owner.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/sp/owner?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ad/user.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ad/user.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ad/user?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/cloud.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/cloud.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/cloud?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/sqlvm-preview/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/sqlvm-preview/sqlvm?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm/aglistener.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm/aglistener.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/sqlvm-preview/sqlvm/aglistener?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm/group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/sqlvm-preview/sqlvm/group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/sqlvm-preview/sqlvm/group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/account.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/ext/storage-preview/storage/account.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ext/storage-preview/storage/account?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/extension.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/extension.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/extension?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/group?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/group/deployment.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/group/deployment.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/group/deployment?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/group/deployment/operation.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/group/deployment/operation.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/group/deployment/operation?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/group/lock.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/group/lock.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/group/lock?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/hdinsight.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/hdinsight.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/hdinsight?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/certificate.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/certificate.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/certificate?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/certificate/contact.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/certificate/contact.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/certificate/contact?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/certificate/issuer.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/certificate/issuer.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/certificate/issuer?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/certificate/issuer/admin.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/certificate/issuer/admin.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/certificate/issuer/admin?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/certificate/pending.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/certificate/pending.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/certificate/pending?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/key.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/key.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/key?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/keyvault/secret.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/keyvault/secret.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/keyvault/secret?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/lock.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/lock.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/lock?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/address-pool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/address-pool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/address-pool?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/auth-cert.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/auth-cert.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/auth-cert?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-ip.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-ip.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/frontend-ip?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-port.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/frontend-port.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/frontend-port?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-listener.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-listener.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/http-listener?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-settings.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/http-settings.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/http-settings?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/network/application-gateway/probe.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/network/application-gateway/probe.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/network/application-gateway/probe?view=azure-cli-2017-03-09-profile&branch=pr-en-us-47) (azure-cli-2017-03-09-profile) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C17%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201812170723454220-47%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=InbksLeBKJr62Oo4g3h4u0UIJP%2Blk41AOuxAyo3pXiw%3D&st=2018-12-17T07%3A48%3A38Z&se=2019-01-17T07%3A53%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
