### PR TITLE
merge master into live-based

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-peliao-zz** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

:clock10: **Pending**: waiting for processors ([33](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 8 sec(s)_

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201902200621573166-50%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=duCXPebK3N5OGuR2WDJMuZ318Q6UlDYetAE%2FYpWvx4c%3D&st=2019-02-20T06%3A42%3A23Z&se=2019-03-23T06%3A47%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

:clock10: **Pending**: waiting for processors ([114](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **OPS Build is busy**, click [here](https://sitehelp.microsoft.com/) to report any potential performance downgrade issues, or you could view [OPS Portal](https://ops.microsoft.com/#/statistic) for trend of build queue length.

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 8 sec(s)_

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

:clock10: **Incremental building**: average incremental building time is _12 min(s) 39 sec(s)_

**Comment by v-susu-zz** [comment]
OPS Build status updates of commit _[9540eaa](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/pull/50/commits/9540eaa90d599e7a8ac46d428e4e650f633b006d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2018-03-01-hybrid/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/authenticate-azure-cli?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/authenticate-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/authenticate-azure-cli?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/azure-cli-extensions-list.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/azure-cli-extensions-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-extensions-list?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/format-output-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/format-output-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/format-output-azure-cli?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/format-output-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/format-output-azure-cli?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/get-started-with-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/get-started-with-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/get-started-with-azure-cli?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/get-started-with-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/get-started-with-azure-cli?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/includes/current-version.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/includes/current-version.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest) |
[docs-ref-conceptual/includes/linux-install-requirements.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/includes/linux-install-requirements.md) | :white_check_mark:Succeeded | |
[docs-ref-conceptual/includes/rpm-warning.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/includes/rpm-warning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest) |
[docs-ref-conceptual/index.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/index?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/index?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/index?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-apt?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-linux.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-linux?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-linux?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-linux?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-macos.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-macos.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-macos?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-macos?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-macos?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-windows.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-windows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-windows?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-windows?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-windows?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-yum.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-yum.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-yum?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-yum?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-yum?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli-zypper.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-zypper.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli-zypper?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[docs-ref-conceptual/install-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli?view=azure-cli-2017-03-09-profile&branch=pr-en-us-50) (azure-cli-2017-03-09-profile)<br/> [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/install-azure-cli?view=azure-cli-2018-03-01-hybrid&branch=pr-en-us-50) (azure-cli-2018-03-01-hybrid) |
[latest/docs-ref-autogen/ams/asset.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/ams/asset.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/ams/asset?view=azure-cli-latest&branch=pr-en-us-50) (azure-cli-latest) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201902200733039367-50%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eyT5WlChc5y%2Bcn8rpmXHxQTfc0h6mS2GHNWiXSzTP1Y%3D&st=2019-02-20T07%3A46%3A53Z&se=2019-03-23T07%3A51%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
