### PR TITLE
merge master into live-based

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by v-peliao-zz** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch live-based has been deleted or has been force pushed: fatal: Could not parse object &#39;72b18aaefde6b3e78c696bfbbc21c07a1ccc0e8f&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201711100530314193-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Trizj9%2BbX3Wkvo2HcN1Fxn%2BZwOnmPh6Lb7TbY%2BLHU10%3D&st=2017-11-10T05%3A25%3A49Z&se=2017-12-11T05%3A30%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch live-based has been deleted or has been force pushed: fatal: Could not parse object &#39;72b18aaefde6b3e78c696bfbbc21c07a1ccc0e8f&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201711100541591367-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GZTWiyMWDxsx%2BGdPunclKSk0N7RFNAdrSOIfFO17v8E%3D&st=2017-11-10T05%3A37%3A18Z&se=2017-12-11T05%3A42%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch live-based has been deleted or has been force pushed: fatal: Could not parse object &#39;72b18aaefde6b3e78c696bfbbc21c07a1ccc0e8f&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201711100543001949-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TsIi%2BC2g3nNrPe0nFm2%2FBMVRy9qCbf3B%2Brem7nmlslw%3D&st=2017-11-10T05%3A38%3A18Z&se=2017-12-11T05%3A43%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified commit because branch live-based has been deleted or has been force pushed: fatal: Could not parse object &#39;72b18aaefde6b3e78c696bfbbc21c07a1ccc0e8f&#39;.


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201711100544397233-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=u4%2FuF30LP3FRXSNbM9uuGpkgqIK9hLrCNbpZ1PVvByY%3D&st=2017-11-10T05%3A39%3A56Z&se=2017-12-11T05%3A44%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao-zz** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[2017-03-09-profile/docs-ref-autogen/storage/account.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/storage/account.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-2017-03-09-profile/storage/account?view=azure-cli-2017-03-09-profile&branch=pr-en-us-22) (azure-cli-2017-03-09-profile) |
[2017-03-09-profile/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/2017-03-09-profile/docs-ref-autogen/webapp/deployment/source.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-2017-03-09-profile/webapp/deployment/source?view=azure-cli-2017-03-09-profile&branch=pr-en-us-22) (azure-cli-2017-03-09-profile) |
[latest/docs-ref-autogen/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/firewall-rule?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acr.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acr?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acr/credential.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/credential.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acr/credential?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acr/replication.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/replication.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acr/replication?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acr/repository.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/repository.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acr/repository?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acr/webhook.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acr/webhook.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acr/webhook?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acs.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acs?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acs/dcos.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acs/dcos.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acs/dcos?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/acs/kubernetes.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/acs/kubernetes.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/acs/kubernetes?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/aks.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/aks.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/aks?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/dls/fs.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/dls/fs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/dls/fs?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/functionapp/deployment/source.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/functionapp/deployment/source.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/functionapp/deployment/source?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/index.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/index?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/action-group.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/action-group.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/action-group?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/activity-log.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/activity-log.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/activity-log?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/alert.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/alert.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/alert?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/autoscale-settings.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/autoscale-settings.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/autoscale-settings?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/diagnostic-settings.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/diagnostic-settings.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/diagnostic-settings?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/log-profiles.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/log-profiles.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/log-profiles?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/monitor/metrics.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/monitor/metrics.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/monitor/metrics?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/mysql/server/firewall-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/mysql/server/firewall-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/mysql/server/firewall-rule?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/policy/definition.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/policy/definition.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/policy/definition?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/postgres/server/firewall-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/postgres/server/firewall-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/postgres/server/firewall-rule?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db/audit-policy.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db/audit-policy.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db/audit-policy?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db/op.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db/op.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db/op?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db/replica.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db/replica.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db/replica?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db/tde.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db/tde.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db/tde?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/db/threat-policy.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/db/threat-policy.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/db/threat-policy?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/dw.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/dw.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/dw?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/elastic-pool.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/elastic-pool.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/elastic-pool?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server/ad-admin.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server/ad-admin.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/ad-admin?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server/firewall-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server/firewall-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/firewall-rule?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server/key.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server/key.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/key?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server/tde-key.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server/tde-key.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/tde-key?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/sql/server/vnet-rule.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/sql/server/vnet-rule.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/sql/server/vnet-rule?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/taskhelp.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/taskhelp.yml) | :white_check_mark:Succeeded | |
[latest/docs-ref-autogen/vmss.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/vmss.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/vmss?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-autogen/webapp/deployment/source.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-autogen/webapp/deployment/source.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/webapp/deployment/source?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-conceptual/TOC.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/TOC.md) | :white_check_mark:Succeeded | |
[latest/docs-ref-conceptual/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/create-an-azure-service-principal-azure-cli?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-conceptual/authenticate-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/authenticate-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/authenticate-azure-cli?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-conceptual/azure-cli-extensions.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/azure-cli-extensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/azure-cli-extensions?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/create-an-azure-service-principal-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/create-an-azure-service-principal-azure-cli?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |
[latest/docs-ref-conceptual/install-azure-cli.md](https://github.com/OPS-E2E-Prod/azure-docs-cli-python/blob/master/latest/docs-ref-conceptual/install-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azure-cli-docs/azure-cli-latest/install-azure-cli?view=azure-cli-latest&branch=pr-en-us-22) (azure-cli-latest) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C10%5C0762c6d6-cb91-510a-10b9-a881d0bb3e83%5CPullRequest%5C201711100612279741-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZDm8yWB87DjaFsEEXcF%2F1kffv2KCYNoOt3LYkhG9taU%3D&st=2017-11-10T06%3A10%3A03Z&se=2017-12-11T06%3A15%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
